### PR TITLE
fix(backward-compatibility): make warnings fix with Ecto 3.2 backward compatible with Ecto 2.x

### PR DESCRIPTION
**Pull request by seantanly**
Ref: https://github.com/sobolevn/ecto_autoslug_field/pull/100

### CODE REVIEW

**Comment by seantanly** [comment]
@sobolevn may we have a new minor release with the above fix soon? 🙂

**Comment by sobolevn** [comment]
Will do today

**Comment by sobolevn** [comment]
Sorry, @seantanly! It took me so long to release a new version. Please, feel free to submit your feedback about `2.0.1`

**Comment by seantanly** [comment]
@sobolevn Thanks for cutting the new release! So far no issues with `2.0.1`, will feedback if any. :)

**Pull request merged**
