### PR TITLE
Ecto 2 support

### PR DESCRIPTION
**Pull request by nlap**
Thanks for publishing this library. I made some small updates necessary for Ecto 2 compatibility.

### CODE REVIEW

**Comment by sobolevn** [comment]
Thanks! That's an awesome and valuable contribution! Please, have a look at my feedback. I will merge it as soon as possible.

**Comment by nlap** [comment]
I think supporting only ecto 2 by default is reasonable, all new Phoenix projects use 2, for example.

If someone still needs Ecto 1 they can specify ecto_autoslug_field 0.1.3. Added a commit to improve on this:

- Ecto ~>1.0 instructions added to the readme 
- Changed dep version to cover all of ecto 2.0

Let me know if you have any other feedback

**Comment by sobolevn** [comment]
Great! Thank you!

**Comment by sobolevn** [comment]
I will release it shortly.

**Pull request merged**
